import type { Locale } from "@/lib/i18n/dictionaries"

const text = {
  en: {
    todo: {
      tasksLeft: (n: number) => `${n} task${n === 1 ? "" : "s"} left`,
      clearAll: "Clear all",
      placeholder: "Write a task…",
      add: "Add",
      empty: "No tasks yet — add one above",
      markDone: "Mark as done",
      markNotDone: "Mark as not done",
      deleteTask: "Delete",
    },
    pomodoro: {
      focus: "Focus",
      shortBreak: "Short break",
      longBreak: "Long break",
      start: "Start",
      pause: "Pause",
      reset: "Reset",
      session: "Session",
      sessionsUntilLong: "sessions until long break",
      phase: (n: number) => (n === 1 ? "Focus" : n === 2 ? "Short break" : "Long break"),
    },
    stopwatch: {
      start: "Start",
      pause: "Pause",
      reset: "Reset",
      lap: "Lap",
      lapsEmpty: "No laps yet — press Lap during a run.",
      clear: "Clear laps",
    },
    typing: {
      wpm: "WPM",
      accuracy: "Accuracy",
      done: "Done!",
      pressStart: "Press Start, then type what you see.",
      typeHere: "Type here…",
      start: "Start",
      reset: "Reset",
    },
    memory: {
      moves: "Moves",
      matched: "Matched",
      restart: "Restart",
      win: (moves: number) => `You solved it in ${moves} moves!`,
    },
    slot: {
      spin: "Spin",
      score: "Score",
      ready: "Ready",
    },
    colorMixer: {
      title: "RGB Mixer",
      r: "R",
      g: "G",
      b: "B",
      hex: "Hex",
    },
    landingPage: {
      navHome: "Home",
      navFeatures: "Features",
      navPricing: "Pricing",
      navFaq: "FAQ",
      navCta: "Start free",
      heroBadge: "AI workflows are now live",
      heroTitle: "Ship beautiful products, on time",
      heroSub:
        "Nebula brings analytics, automation and collaboration into one calm workspace for modern product teams.",
      heroPlaceholder: "Enter your work email",
      heroCta: "Get started",
      heroNote: "Free 14-day trial · No credit card required",
      heroImageAlt: "Nebula team collaborating on a project",
      heroStats: [
        { value: "4,200+", label: "Projects shipped" },
        { value: "1,900+", label: "Active teams" },
        { value: "31%", label: "Avg. time saved" },
      ],
      featuresTitle: "Everything your team needs",
      featuresSub: "One platform, zero friction. Each tool is built to stay out of your way.",
      features: [
        { title: "Real-time analytics", desc: "Dashboards refresh the moment your data changes." },
        { title: "Visual automations", desc: "Build workflows with a drag-and-drop canvas — no code." },
        { title: "Team collaboration", desc: "Comments, mentions and live cursors in every document." },
        { title: "Universal search", desc: "Find any file, message or metric in milliseconds." },
        { title: "Bank-grade security", desc: "SOC 2, SSO/SAML and encryption at rest by default." },
        { title: "Integrations", desc: "200+ integrations with the tools you already use." },
      ],
      pricingTitle: "Simple, predictable pricing",
      pricingSub: "Start free and scale when you're ready. No hidden fees, cancel anytime.",
      monthly: "Monthly",
      yearly: "Yearly",
      savePercent: "Save 20%",
      perMonth: "/mo",
      choosePlan: "Choose plan",
      currentPlan: "Your plan",
      plans: [
        {
          name: "Starter",
          price: [12, 9],
          desc: "For small teams getting started.",
          features: ["Up to 5 members", "Core analytics", "Community support"],
        },
        {
          name: "Growth",
          price: [29, 23],
          desc: "For teams that are scaling fast.",
          features: ["Unlimited members", "Advanced analytics", "Automations", "Priority support"],
        },
        {
          name: "Scale",
          price: [79, 63],
          desc: "For companies with big ambitions.",
          features: ["Everything in Growth", "SSO/SAML", "Dedicated success manager", "99.99% uptime SLA"],
        },
      ],
      faqTitle: "Frequently asked questions",
      faqItems: [
        { q: "Can I cancel anytime?", a: "Yes. Plans are month-to-month and you can cancel in two clicks — no calls, no retention scripts." },
        { q: "Is my data secure?", a: "We use encryption in transit and at rest, and offer SSO/SAML on every paid plan." },
        { q: "Do you offer discounts?", a: "Annual billing saves you 20%. Nonprofits and education teams get additional discounts." },
        { q: "How does the trial work?", a: "Start free for 14 days — full features, no credit card. If you like it, pick a plan." },
      ],
      footerProduct: "Product",
      footerCompany: "Company",
      footerLegal: "Legal",
      footerCol1: ["Features", "Pricing", "Integrations", "Changelog"],
      footerCol2: ["About", "Blog", "Careers", "Contact"],
      footerCol3: ["Privacy", "Terms", "Security", "Cookies"],
      footerTagline: "The calm workspace for modern product teams.",
      copyright: "© 2026 Nebula Inc. All rights reserved.",
    },
    shopPage: {
      currency: "$",
      brand: "Wedge",
      searchPlaceholder: "Search products…",
      filters: ["All", "Apparel", "Electronics", "Accessories"],
      noResults: "No products match your search.",
      cartEmpty: "Your cart is empty.",
      cart: "Cart",
      item: (n: number) => `${n} item${n === 1 ? "" : "s"}`,
      checkout: "Checkout",
      subtotal: "Subtotal",
      clearCart: "Clear cart",
      placeOrder: "Place order",
      orderPlaced: "Order placed!",
      freeShipping: "Free shipping over $100",
      products: [
        { name: "Essential White Tee", category: "Apparel", price: 68, image: "/images/shop/crewneck.jpg" },
        { name: "Aero Runner Sneakers", category: "Apparel", price: 92, image: "/images/shop/sneakers.jpg" },
        { name: "Pulse Wireless Headphones", category: "Electronics", price: 149, image: "/images/shop/headphones.jpg" },
        { name: "Vega Smart Watch", category: "Electronics", price: 219, image: "/images/shop/watch.jpg" },
        { name: "Trail 22L Backpack", category: "Accessories", price: 59, image: "/images/shop/backpack.jpg" },
        { name: "Orbit Power Bank", category: "Accessories", price: 39, image: "/images/shop/powerbank.jpg" },
      ],
    },
    userDashboardPage: {
      greeting: "Good morning,",
      youName: "Alex Carter",
      navOverview: "Overview",
      navAnalytics: "Analytics",
      navMessages: "Messages",
      navSettings: "Settings",
      overviewLabel: "Overview",
      analyticsLabel: "Analytics",
      messagesLabel: "Messages",
      settingsLabel: "Settings",
      stats: [
        { label: "Revenue", value: "$48,290" },
        { label: "Active users", value: "2,314" },
        { label: "Orders", value: "1,208" },
        { label: "Conversion", value: "3.6%" },
      ],
      chartTitle: "Revenue · last 7 months",
      chartMonths: ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"],
      chartValues: [34, 42, 38, 55, 47, 61, 74],
      activityTitle: "Recent activity",
      activity: [
        { text: "Payment received from Northwind Inc.", time: "2m ago" },
        { text: "Order #4821 shipped", time: "25m ago" },
        { text: "New teammate joined #design", time: "1h ago" },
        { text: "Invoice #3390 was paid", time: "3h ago" },
      ],
      messagesTitle: "Messages",
      markAllRead: "Mark all as read",
      allRead: "All caught up!",
      messages: [
        { from: "Maya Lin", text: "The new dashboard is looking sharp — shipped!", time: "10m", unread: true },
        { from: "Jonas Weber", text: "Can you review the proposal before Friday?", time: "1h", unread: true },
        { from: "Sara Okafor", text: "Met with Acme today. They want a quote.", time: "3h", unread: false },
        { from: "Team Standup", text: "Notes from this morning are live.", time: "Yesterday", unread: false },
      ],
      settingsTitle: "Settings",
      notifications: "Email notifications",
      notificationsDesc: "Get a digest of activity in your projects.",
      weeklyReport: "Weekly report",
      weeklyReportDesc: "A summary of your metrics every Monday.",
      twoFactor: "Two-factor auth",
      twoFactorDesc: "Extra security for your account.",
    },
    mapExplorer: {
      searchPlaceholder: "Search branches…",
      listTitle: "Branches",
      myLocation: "My location",
      locating: "Locating…",
      locationError: "Couldn't get your location.",
      noResults: "No branches match your search.",
      layers: { streets: "Streets", satellite: "Satellite" },
      branches: [
        { name: "Bangkok · HQ", address: "Sathorn, Bangkok", lat: 13.7563, lng: 100.5018 },
        { name: "Chiang Mai", address: "Nimman, Chiang Mai", lat: 18.7883, lng: 98.9853 },
        { name: "Phuket", address: "Patong, Phuket", lat: 7.8804, lng: 98.3923 },
        { name: "Pattaya", address: "Beach Road, Chonburi", lat: 12.9236, lng: 100.8771 },
        { name: "Khon Kaen", address: "Nai Mueang, Khon Kaen", lat: 16.4322, lng: 102.8236 },
      ],
    },
    adminDashboardPage: {
      navOverview: "Overview",
      navMembers: "Members",
      navOrders: "Orders",
      overviewLabel: "Overview",
      membersLabel: "Members",
      ordersLabel: "Orders",
      stats: [
        { label: "Revenue", value: "$128,430" },
        { label: "Members", value: "8,421" },
        { label: "Orders", value: "3,204" },
        { label: "Conversion", value: "4.7%" },
      ],
      chartTitle: "Revenue · last 7 months",
      chartMonths: ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"],
      chartValues: [22, 31, 38, 46, 43, 58, 65],
      membersTitle: "Members",
      searchPlaceholder: "Search name or email…",
      colName: "Name",
      colEmail: "Email",
      colRole: "Role",
      colStatus: "Status",
      colAction: "Action",
      roles: { admin: "Admin", editor: "Editor", member: "Member" },
      statuses: { active: "Active", blocked: "Blocked", pending: "Pending" },
      block: "Block",
      unblock: "Unblock",
      filterAll: "All",
      filterActive: "Active",
      filterBlocked: "Blocked",
      filterPending: "Pending",
      members: [
        { name: "Olivia Bennett", email: "olivia@acme.dev", role: "admin", status: "active" },
        { name: "Liam Chen", email: "liam@acme.dev", role: "editor", status: "active" },
        { name: "Noah Patel", email: "noah@acme.dev", role: "member", status: "pending" },
        { name: "Emma Rossi", email: "emma@acme.dev", role: "member", status: "blocked" },
        { name: "Ava Kim", email: "ava@acme.dev", role: "editor", status: "active" },
        { name: "Lucas Moreau", email: "lucas@acme.dev", role: "member", status: "active" },
      ],
      ordersTitle: "Orders",
      colOrder: "Order",
      colCustomer: "Customer",
      colDate: "Date",
      colTotal: "Total",
      orderStatuses: { paid: "Paid", pending: "Pending", refunded: "Refunded" },
      orders: [
        { id: "#10482", customer: "Olivia Bennett", date: "Sep 4", total: "$1,240", status: "paid" },
        { id: "#10481", customer: "Liam Chen", date: "Sep 3", total: "$890", status: "paid" },
        { id: "#10480", customer: "Noah Patel", date: "Sep 3", total: "$320", status: "pending" },
        { id: "#10479", customer: "Emma Rossi", date: "Sep 1", total: "$1,050", status: "refunded" },
        { id: "#10478", customer: "Ava Kim", date: "Aug 31", total: "$640", status: "paid" },
        { id: "#10477", customer: "Lucas Moreau", date: "Aug 30", total: "$215", status: "pending" },
      ],
    },
  },
  th: {
    todo: {
      tasksLeft: (n: number) => `เหลืออีก ${n} งาน`,
      clearAll: "ล้างทั้งหมด",
      placeholder: "เขียนงานที่ต้องทำ…",
      add: "เพิ่ม",
      empty: "ยังไม่มีงาน — เพิ่มด้านบนได้เลย",
      markDone: "ทำเครื่องหมายว่าเสร็จ",
      markNotDone: "ทำเครื่องหมายว่ายังไม่เสร็จ",
      deleteTask: "ลบ",
    },
    pomodoro: {
      focus: "โฟกัส",
      shortBreak: "พักสั้น",
      longBreak: "พักยาว",
      start: "เริ่ม",
      pause: "หยุด",
      reset: "รีเซ็ต",
      session: "เซสชัน",
      sessionsUntilLong: "เซสชันจะถึงพักยาว",
      phase: (n: number) =>
        n === 1 ? "โฟกัส" : n === 2 ? "พักสั้น" : "พักยาว",
    },
    stopwatch: {
      start: "เริ่ม",
      pause: "หยุด",
      reset: "รีเซ็ต",
      lap: "แลป",
      lapsEmpty: "ยังไม่มีแลป — กดแลประหว่างวิ่งครับ",
      clear: "ล้างแลป",
    },
    typing: {
      wpm: "คำ/นาที",
      accuracy: "ความแม่นยำ",
      done: "เสร็จแล้ว!",
      pressStart: "กดเริ่ม แล้วพิมพ์ตามที่เห็นครับ",
      typeHere: "พิมพ์ตรงนี้…",
      start: "เริ่ม",
      reset: "รีเซ็ต",
    },
    memory: {
      moves: "การเปิด",
      matched: "ที่จับคู่ได้",
      restart: "เริ่มใหม่",
      win: (moves: number) => `เก่งมาก! เปิดทั้งหมด ${moves} ครั้งก็ชนะแล้ว!`,
    },
    slot: {
      spin: "ปั่น",
      score: "คะแนน",
      ready: "พร้อม",
    },
    colorMixer: {
      title: "มิกเซอร์สี RGB",
      r: "R",
      g: "G",
      b: "B",
      hex: "เลขสี",
    },
    landingPage: {
      navHome: "หน้าแรก",
      navFeatures: "ฟีเจอร์",
      navPricing: "ราคา",
      navFaq: "คำถามที่พบบ่อย",
      navCta: "เริ่มใช้ฟรี",
      heroBadge: "ปล่อย AI workflows แล้ววันนี้",
      heroTitle: "ส่งมอบโปรดักต์ที่สวย ตรงตามกำหนด",
      heroSub:
        "Nebula รวม analytics, automation และการทำงานร่วมกันไว้ในพื้นที่ทำงานเดียวที่สงบ สำหรับทีมโปรดักต์ยุคใหม่",
      heroPlaceholder: "กรอกอีเมลที่ทำงาน",
      heroCta: "เริ่มต้นใช้งาน",
      heroNote: "ทดลองใช้ฟรี 14 วัน · ไม่ต้องใช้บัตรเครดิต",
      heroImageAlt: "ทีม Nebula กำลังร่วมมือกันในโปรเจกต์",
      heroStats: [
        { value: "4,200+", label: "โปรเจกต์ที่ส่งมอบ" },
        { value: "1,900+", label: "ทีมที่ใช้งาน" },
        { value: "31%", label: "เวลาที่ประหยัดเฉลี่ย" },
      ],
      featuresTitle: "ครบทุกอย่างที่ทีมต้องการ",
      featuresSub: "หนึ่งแพลตฟอร์ม ไม่มีสะดุด แต่ละเครื่องมือถูกออกแบบให้ไม่กวนใจคุณ",
      features: [
        { title: "Analytics แบบเรียลไทม์", desc: "แดชบอร์ดอัปเดตทันทีเมื่อข้อมูลเปลี่ยน" },
        { title: "Automation แบบภาพ", desc: "สร้าง workflow ด้วยการลากวางบนแคนวาส — ไม่ต้องเขียนโค้ด" },
        { title: "ทำงานร่วมกันในทีม", desc: "คอมเมนต์ แท็ก และ live cursor ในทุกเอกสาร" },
        { title: "ค้นหาทั้งระบบ", desc: "หาไฟล์ ข้อความ หรือเมตริกได้ในมิลลิวินาที" },
        { title: "ความปลอดภัยระดับธนาคาร", desc: "SOC 2, SSO/SAML และการเข้ารหัสตามค่าเริ่มต้น" },
        { title: "ต่อเชื่อมทุกเครื่องมือ", desc: "อินทิเกรชันกว่า 200+ ตัวกับเครื่องมือที่ใช้อยู่" },
      ],
      pricingTitle: "ราคาง่าย มองเห็นข้างหน้า",
      pricingSub: "เริ่มฟรี ขยายเมื่อพร้อม ไม่มีค่าใช้จ่ายแอบแฝง ยกเลิกเมื่อไหร่ก็ได้",
      monthly: "รายเดือน",
      yearly: "รายปี",
      savePercent: "ประหยัด 20%",
      perMonth: "/เดือน",
      choosePlan: "เลือกแพ็กเกจ",
      currentPlan: "แพ็กเกจของคุณ",
      plans: [
        {
          name: "Starter",
          price: [12, 9],
          desc: "สำหรับทีมเล็กที่เริ่มต้น",
          features: ["สูงสุด 5 คน", "Analytics หลัก", "ซัพพอร์ตชุมชน"],
        },
        {
          name: "Growth",
          price: [29, 23],
          desc: "สำหรับทีมที่ขยายตัวเร็ว",
          features: ["สมาชิกไม่จำกัด", "Analytics ขั้นสูง", "Automations", "ซัพพอร์ตลำดับแรก"],
        },
        {
          name: "Scale",
          price: [79, 63],
          desc: "สำหรับบริษัทที่มีเป้าหมายใหญ่",
          features: ["ทุกอย่างใน Growth", "SSO/SAML", "ผู้จัดการความสำเร็จส่วนตัว", "SLA 99.99%"],
        },
      ],
      faqTitle: "คำถามที่พบบ่อย",
      faqItems: [
        { q: "ยกเลิกได้ตลอดไหม?", a: "ได้ครับ แพ็กเกจเป็นรายเดือน ยกเลิกได้ในสองคลิก — ไม่มีสายเรียกต่อรองใด ๆ" },
        { q: "ข้อมูลปลอดภัยไหม?", a: "เราเข้ารหัสทั้งขณะส่งและจัดเก็บ และรองรับ SSO/SAML ในทุกแพ็กเกจที่ชำระเงิน" },
        { q: "มีส่วนลดไหม?", a: "การบิลรายปีประหยัด 20% และทีมองค์กรไม่แสวงหากำไร / การศึกษาได้ส่วนลดเพิ่ม" },
        { q: "ทดลองใช้ยังไง?", a: "เริ่มฟรี 14 วัน — ฟีเจอร์ครบ ไม่ต้องใช้บัตรเครดิต แล้วค่อยเลือกแพ็กเกจที่ชอบ" },
      ],
      footerProduct: "ผลิตภัณฑ์",
      footerCompany: "บริษัท",
      footerLegal: "กฎหมาย",
      footerCol1: ["ฟีเจอร์", "ราคา", "Integrations", "Changelog"],
      footerCol2: ["เกี่ยวกับเรา", "บล็อก", "งาน", "ติดต่อ"],
      footerCol3: ["ความเป็นส่วนตัว", "เงื่อนไข", "ความปลอดภัย", "คุกกี้"],
      footerTagline: "พื้นที่ทำงานอันสงบ สำหรับทีมโปรดักต์ยุคใหม่",
      copyright: "© 2026 Nebula Inc. สงวนลิขสิทธิ์",
    },
    shopPage: {
      currency: "฿",
      brand: "Wedge",
      searchPlaceholder: "ค้นหาสินค้า…",
      filters: ["ทั้งหมด", "เสื้อผ้า", "อิเล็กทรอนิกส์", "เครื่องประดับ"],
      noResults: "ไม่พบสินค้าที่ตรงกับการค้นหา",
      cartEmpty: "ตะกร้ายังว่างอยู่",
      cart: "ตะกร้า",
      item: (n: number) => `${n} รายการ`,
      checkout: "ชำระเงิน",
      subtotal: "ยอดรวม",
      clearCart: "ล้างตะกร้า",
      placeOrder: "สั่งซื้อ",
      orderPlaced: "สั่งซื้อสำเร็จ!",
      freeShipping: "ส่งฟรีเมื่อซื้อครบ ฿500",
      products: [
        { name: "เสื้อยืดขาว Essential", category: "เสื้อผ้า", price: 68, image: "/images/shop/crewneck.jpg" },
        { name: "รองเท้า Aero Runner", category: "เสื้อผ้า", price: 92, image: "/images/shop/sneakers.jpg" },
        { name: "หูฟังไร้สาย Pulse", category: "อิเล็กทรอนิกส์", price: 149, image: "/images/shop/headphones.jpg" },
        { name: "สมาร์ทวอทช์ Vega", category: "อิเล็กทรอนิกส์", price: 219, image: "/images/shop/watch.jpg" },
        { name: "กระเป๋า Trail 22L", category: "เครื่องประดับ", price: 59, image: "/images/shop/backpack.jpg" },
        { name: "พาวเวอร์แบงก์ Orbit", category: "เครื่องประดับ", price: 39, image: "/images/shop/powerbank.jpg" },
      ],
    },
    userDashboardPage: {
      greeting: "สวัสดีตอนเช้า",
      youName: "อเล็กซ์ คาร์เตอร์",
      navOverview: "ภาพรวม",
      navAnalytics: "การวิเคราะห์",
      navMessages: "ข้อความ",
      navSettings: "ตั้งค่า",
      overviewLabel: "ภาพรวม",
      analyticsLabel: "การวิเคราะห์",
      messagesLabel: "ข้อความ",
      settingsLabel: "ตั้งค่า",
      stats: [
        { label: "รายได้", value: "฿48,290" },
        { label: "ผู้ใช้ที่ใช้งาน", value: "2,314" },
        { label: "ออเดอร์", value: "1,208" },
        { label: "คอนเวอร์ชัน", value: "3.6%" },
      ],
      chartTitle: "รายได้ · 7 เดือนย้อนหลัง",
      chartMonths: ["ก.พ.", "มี.ค.", "เม.ย.", "พ.ค.", "มิ.ย.", "ก.ค.", "ส.ค."],
      chartValues: [34, 42, 38, 55, 47, 61, 74],
      activityTitle: "กิจกรรมล่าสุด",
      activity: [
        { text: "รับชำระเงินจาก Northwind Inc.", time: "เมื่อ 2 นาที" },
        { text: "จัดส่งออเดอร์ #4821", time: "เมื่อ 25 นาที" },
        { text: "สมาชิกใหม่เข้าร่วม #design", time: "เมื่อ 1 ชม." },
        { text: "ชำระใบแจ้งหนี้ #3390", time: "เมื่อ 3 ชม." },
      ],
      messagesTitle: "ข้อความ",
      markAllRead: "ทำเครื่องหมายว่าอ่านแล้วทั้งหมด",
      allRead: "อ่านครบทุกข้อความแล้ว!",
      messages: [
        { from: "มายา ลิน", text: "แดชบอร์ดใหม่ดูดีมาก — ส่งให้แล้ว!", time: "10 นาที", unread: true },
        { from: "โจนาส เวเบอร์", text: "ช่วยรีวิวโปรพาซัลก่อนวันศุกร์หน่อย", time: "1 ชม.", unread: true },
        { from: "ซาร่า โอคาฟอร์", text: "วันนี้ไปเจอ Acme มา เขาอยากได้ใบเสนอราคา", time: "3 ชม.", unread: false },
        { from: "ทีม Standup", text: "บันทึกประชุมรอบเช้าอัปเดตแล้ว", time: "เมื่อวาน", unread: false },
      ],
      settingsTitle: "ตั้งค่า",
      notifications: "อีเมลแจ้งเตือน",
      notificationsDesc: "รับสรุปกิจกรรมในโปรเจกต์ของคุณทางอีเมล",
      weeklyReport: "รายงานประจำสัปดาห์",
      weeklyReportDesc: "สรุปเมตริกทุกวันจันทร์",
      twoFactor: "ยืนยันตัวตนสองชั้น",
      twoFactorDesc: "ความปลอดภัยพิเศษสำหรับบัญชีของคุณ",
    },
    mapExplorer: {
      searchPlaceholder: "ค้นหาสาขา…",
      listTitle: "สาขา",
      myLocation: "ตำแหน่งของฉัน",
      locating: "กำลังหาตำแหน่ง…",
      locationError: "หาตำแหน่งของคุณไม่เจอ",
      noResults: "ไม่พบสาขาที่ตรงกับการค้นหา",
      layers: { streets: "ถนน", satellite: "ดาวเทียม" },
      branches: [
        { name: "กรุงเทพฯ · สำนักงานใหญ่", address: "สาทร กรุงเทพฯ", lat: 13.7563, lng: 100.5018 },
        { name: "เชียงใหม่", address: "นิมมาน เชียงใหม่", lat: 18.7883, lng: 98.9853 },
        { name: "ภูเก็ต", address: "ป่าตอง ภูเก็ต", lat: 7.8804, lng: 98.3923 },
        { name: "พัทยา", address: "ถนนเลียบชายหาด ชลบุรี", lat: 12.9236, lng: 100.8771 },
        { name: "ขอนแก่น", address: "ในเมือง ขอนแก่น", lat: 16.4322, lng: 102.8236 },
      ],
    },
    adminDashboardPage: {
      navOverview: "ภาพรวม",
      navMembers: "สมาชิก",
      navOrders: "ออเดอร์",
      overviewLabel: "ภาพรวม",
      membersLabel: "สมาชิก",
      ordersLabel: "ออเดอร์",
      stats: [
        { label: "รายได้", value: "฿128,430" },
        { label: "สมาชิก", value: "8,421" },
        { label: "ออเดอร์", value: "3,204" },
        { label: "คอนเวอร์ชัน", value: "4.7%" },
      ],
      chartTitle: "รายได้ · 7 เดือนย้อนหลัง",
      chartMonths: ["ก.พ.", "มี.ค.", "เม.ย.", "พ.ค.", "มิ.ย.", "ก.ค.", "ส.ค."],
      chartValues: [22, 31, 38, 46, 43, 58, 65],
      membersTitle: "สมาชิก",
      searchPlaceholder: "ค้นหาชื่อหรืออีเมล…",
      colName: "ชื่อ",
      colEmail: "อีเมล",
      colRole: "บทบาท",
      colStatus: "สถานะ",
      colAction: "จัดการ",
      roles: { admin: "ผู้ดูแล", editor: "บรรณาธิการ", member: "สมาชิก" },
      statuses: { active: "ใช้งานอยู่", blocked: "ถูกบล็อก", pending: "รออนุมัติ" },
      block: "บล็อก",
      unblock: "เลิกบล็อก",
      filterAll: "ทั้งหมด",
      filterActive: "ใช้งานอยู่",
      filterBlocked: "ถูกบล็อก",
      filterPending: "รออนุมัติ",
      members: [
        { name: "Olivia Bennett", email: "olivia@acme.dev", role: "admin", status: "active" },
        { name: "Liam Chen", email: "liam@acme.dev", role: "editor", status: "active" },
        { name: "Noah Patel", email: "noah@acme.dev", role: "member", status: "pending" },
        { name: "Emma Rossi", email: "emma@acme.dev", role: "member", status: "blocked" },
        { name: "Ava Kim", email: "ava@acme.dev", role: "editor", status: "active" },
        { name: "Lucas Moreau", email: "lucas@acme.dev", role: "member", status: "active" },
      ],
      ordersTitle: "ออเดอร์",
      colOrder: "ออเดอร์",
      colCustomer: "ลูกค้า",
      colDate: "วันที่",
      colTotal: "ยอดรวม",
      orderStatuses: { paid: "ชำระแล้ว", pending: "รอชำระ", refunded: "คืนเงินแล้ว" },
      orders: [
        { id: "#10482", customer: "Olivia Bennett", date: "4 ก.ย.", total: "฿1,240", status: "paid" },
        { id: "#10481", customer: "Liam Chen", date: "3 ก.ย.", total: "฿890", status: "paid" },
        { id: "#10480", customer: "Noah Patel", date: "3 ก.ย.", total: "฿320", status: "pending" },
        { id: "#10479", customer: "Emma Rossi", date: "1 ก.ย.", total: "฿1,050", status: "refunded" },
        { id: "#10478", customer: "Ava Kim", date: "31 ส.ค.", total: "฿640", status: "paid" },
        { id: "#10477", customer: "Lucas Moreau", date: "30 ส.ค.", total: "฿215", status: "pending" },
      ],
    },
  },
} as const

export function demoText(locale: Locale) {
  return text[locale]
}

export type DemoText = {
  [K in Locale]: (typeof text)[K]
}